services:
  #BASE DE DATOS
  congelador_db:
    image: postgres:16-alpine
    container_name: congelador_db
    restart: always

    env_file:
      - ./backend/.env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5434:${DB_PORT:-5432}" 

    volumes:
      - pgdata_congeladores:/var/lib/postgresql/data
      - ./backend/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

    networks:
      - congeladores_network

  #IA
  congeladores_ia:
    image: ollama/ollama
    container_name: congeladores_ia
    restart: always
    volumes:
      - ollama_models_congeladores:/root/.ollama
    networks:
      - congeladores_network

  #BACKEND
  congeladores_api:
    build: ./backend
    container_name: congeladores_api
    restart: always
    command: node app.js
    env_file: ./backend/.env
    depends_on:
      - congelador_db
      - congeladores_ia
    ports:
      - "3001:3000"
    networks:
      - congeladores_network

  #WORKER
  congeladores_worker:
    build: ./backend
    container_name: congeladores_worker
    restart: always
    command: node jobs.js
    env_file: ./backend/.env
    depends_on:
      - congelador_db
    networks:
      - congeladores_network

  #FRONT
  congeladores_frontend:
    build: ./frontend
    container_name: congeladores_frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - congeladores_api
    networks:
      - congeladores_network

#seguridad y discos duros virtuales
networks:
  congeladores_network:
    driver: bridge

volumes:
  pgdata_congeladores:
  ollama_models_congeladores: